export interface RichDocCommandContext {
  exec: (command: string, value?: string) => void;
  clearFormat: () => void;
  capturePaint: () => void;
  stepFont: (direction: number) => void;
  ruby: () => void;
  insertEnclosed: () => void;
  styleBlocks: (mutate: (element: HTMLElement) => void) => void;
  insertHTML: (html: string) => void;
  openImagePicker: () => void;
  takeScreenshot: () => void | Promise<void>;
  insertLink: () => void;
  insertBookmark: () => void;
  insertCrossReference: () => void;
  toggleHeaderFooter: (which: 'header' | 'footer') => void;
  insertTextbox: () => void;
  insertSign: () => void;
  openObjectPicker: () => void;
  changeImageLayer: (direction: number) => void;
  notify: (message: string) => void;
  translate: (key: string) => string;
  updateToc: () => void;
  insertNote: (kind: 'fn' | 'en') => void;
  nextNote: () => void;
  showNotes: () => void;
  insertBiblio: () => void;
  insertCaption: () => void;
  insertTableOfFigures: () => void;
  markIndex: () => void;
  buildIndex: (rebuild: boolean) => void;
  toggleSpell: () => void;
  openWordCount: () => void;
  translateSelection: () => void;
  addComment: () => void;
  deleteComment: () => void;
  navigateComment: (direction: number) => void;
  toggleComments: () => void;
  toggleTrackChanges: () => void;
  toggleDiffView: () => void;
  acceptChange: (accept: boolean) => void;
  setView: (view: 'read' | 'web' | 'outline' | undefined) => void;
  toggleRuler: () => void;
  toggleGrid: () => void;
  toggleNavigation: () => void;
  setZoom: (zoom: number) => void;
  fitZoom: (mode: 'page' | 'width') => void;
  openWikipedia: () => void;
}

export function dispatchRichDocCommand(label: string, context: RichDocCommandContext): void {
  switch (label) {
    case '撤销': context.exec('undo'); break;
    case '重做': context.exec('redo'); break;
    case '剪切': context.exec('cut'); break;
    case '复制': context.exec('copy'); break;
    case '格式刷': context.capturePaint(); break;
    case '增大字号': context.stepFont(1); break;
    case '减小字号': context.stepFont(-1); break;
    case '清除格式': context.clearFormat(); break;
    case '加粗': context.exec('bold'); break;
    case '斜体': context.exec('italic'); break;
    case '下划线': context.exec('underline'); break;
    case '删除线': context.exec('strikeThrough'); break;
    case '下标': context.exec('subscript'); break;
    case '上标': context.exec('superscript'); break;
    case '拼音指南': context.ruby(); break;
    case '带圈字符': context.insertEnclosed(); break;
    case '项目符号': context.exec('insertUnorderedList'); break;
    case '编号': context.exec('insertOrderedList'); break;
    case '减少缩进': context.exec('outdent'); break;
    case '增加缩进': context.exec('indent'); break;
    case '左对齐': context.exec('justifyLeft'); break;
    case '居中': context.exec('justifyCenter'); break;
    case '右对齐': context.exec('justifyRight'); break;
    case '两端对齐': context.exec('justifyFull'); break;
    case '分散对齐': context.styleBlocks((element) => { element.style.textAlign = 'justify'; element.style.textAlignLast = 'justify'; }); break;
    case '空白页': context.insertHTML('<div class="rd-pagebreak" contenteditable="false"></div><p><br></p><div class="rd-pagebreak" contenteditable="false"></div>'); break;
    case '分页': context.insertHTML('<div class="rd-pagebreak" contenteditable="false"></div>'); break;
    case '图片': context.openImagePicker(); break;
    case '屏幕截图': void context.takeScreenshot(); break;
    case '链接': context.insertLink(); break;
    case '书签': context.insertBookmark(); break;
    case '交叉引用': context.insertCrossReference(); break;
    case '页眉': context.toggleHeaderFooter('header'); break;
    case '页脚': context.toggleHeaderFooter('footer'); break;
    case '文本框': context.insertTextbox(); break;
    case '签名行': context.insertSign(); break;
    case '对象': context.openObjectPicker(); break;
    case '水平线': context.exec('insertHorizontalRule'); break;
    case '上移一层': context.changeImageLayer(1); break;
    case '下移一层': context.changeImageLayer(-1); break;
    case '选择窗格': context.notify(context.translate('对象选择窗格暂不可用')); break;
    case '更新目录': context.updateToc(); break;
    case '插入脚注': context.insertNote('fn'); break;
    case '插入尾注': context.insertNote('en'); break;
    case '下一条脚注': context.nextNote(); break;
    case '显示备注': context.showNotes(); break;
    case '书目': context.insertBiblio(); break;
    case '管理源': context.notify(context.translate('源管理暂用文档内直接编辑')); break;
    case '插入题注': context.insertCaption(); break;
    case '插入表目录': context.insertTableOfFigures(); break;
    case '标记条目': context.markIndex(); break;
    case '插入索引': context.buildIndex(false); break;
    case '更新索引': context.buildIndex(true); break;
    case '拼写和语法': context.toggleSpell(); break;
    case '字数统计': context.openWordCount(); break;
    case '翻译': context.translateSelection(); break;
    case '新建批注': context.addComment(); break;
    case '删除': context.deleteComment(); break;
    case '上一条': context.navigateComment(-1); break;
    case '下一条': context.navigateComment(1); break;
    case '显示批注': context.toggleComments(); break;
    case '修订': context.toggleTrackChanges(); break;
    case '显示标记': context.toggleDiffView(); break;
    case '接受': context.acceptChange(true); break;
    case '拒绝': context.acceptChange(false); break;
    case '阅读视图': context.setView('read'); break;
    case '页面视图': context.setView(undefined); break;
    case 'Web 版式': context.setView('web'); break;
    case '大纲': context.setView('outline'); break;
    case '标尺': context.toggleRuler(); break;
    case '网格线': context.toggleGrid(); break;
    case '导航窗格': context.toggleNavigation(); break;
    case '100%': context.setZoom(1); break;
    case '单页': context.fitZoom('page'); break;
    case '页宽': context.fitZoom('width'); break;
    case '多页': context.setZoom(0.5); break;
    case '获取加载项':
    case '我的加载项': context.notify(context.translate('加载项市场开发中')); break;
    case '维基百科': context.openWikipedia(); break;
    default: context.notify(context.translate('执行') + ' · ' + context.translate(label));
  }
}
